#!/bin/bash

set -e -o pipefail

apt update

# Install some misc packages
apt install -y \
    cpufrequtils \
    libraspberrypi-bin \
    rt-tests \
    cpuset \
    stress \
    stress-ng \

# install ros2 dependencies to facilitate cross compilation
apt install -y \
    libtinyxml2-dev \
    libyaml-dev \
    libspdlog-dev \
    libyaml-cpp-dev \
    libasio-dev \
    liblttng-ust-dev \
    cmake \
    libpython3-dev \
    liblttng-ctl-dev \
    libeigen3-dev \
    python3-numpy \
    libbullet-dev \
    libacl1-dev \
    curl \
    libcurl4-openssl-dev \
    python3-psutil \
    python3-packaging \
    python3-lark

# clean up to reduce image size
apt-get clean
rm -rf /var/lib/apt/lists/*
